// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/utils/logUtils';

const SUPABASE_URL = "https://iiuiulmvckujakswquvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpdWl1bG12Y2t1amFrc3dxdXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNzExNjUsImV4cCI6MjA1OTY0NzE2NX0.DKmQ_Tjni93VDmukb56yqH8u7IPpXH805_HlpQNMoDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with real-time explicitly enabled
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    realtime: {
      params: {
        eventsPerSecond: 10 // Higher rate limit for real-time events
      }
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true
    }
  }
);

// Initialize real-time on startup if in browser
if (typeof window !== 'undefined') {
  logger.info('Initializing Supabase client with real-time enabled');
  
  // Expose a debug function to check real-time status
  const checkRealtimeStatus = () => {
    if (supabase && supabase.realtime) {
      // @ts-expect-error - Accessing internal property
      const transport = supabase.realtime.transport;
      const status = transport ? transport.state : 'unknown';
      
      logger.info(`Supabase real-time status: ${status}`);
      return status;
    } else {
      logger.error('Supabase real-time not initialized');
      return null;
    }
  };
  
  // @ts-expect-error - Adding to window for debugging
  window.checkRealtimeStatus = checkRealtimeStatus;
}